// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('BTN ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('BTN ', async function() {
    await driver.get("https://www.btn.co.id/")
    await driver.manage().window().setRect({ width: 1918, height: 1030 })
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    await driver.findElement(By.id("SourceNumber")).click()
    await driver.findElement(By.id("SourceNumber")).sendKeys("1")
    await driver.findElement(By.id("Result")).click()
    await driver.findElement(By.css(".col-sm-3:nth-child(7) #CurrencyCode")).click()
    {
      const dropdown = await driver.findElement(By.css(".col-sm-3:nth-child(7) #CurrencyCode"))
      await dropdown.findElement(By.xpath("//option[. = 'IDR']")).click()
    }
    await driver.findElement(By.id("Result")).click()
    await driver.findElement(By.id("Result")).sendKeys("2")
    await driver.findElement(By.css(".btn-secondary")).click()
  })
})
